# Generated by Django 4.1.4 on 2022-12-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenth_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('inter_marks', models.PositiveIntegerField()),
                ('degree_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('skills', models.CharField(max_length=200)),
                ('work_experience', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
